xarray_feature_scale:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    WaterLevel:
      dims: []
      attrs: {}
      data: 0.5037685036659241
    specific_humidity:
      dims: []
      attrs: {}
      data: 0.004448083229362965
    temperature:
      dims: []
      attrs: {}
      data: 10.237500190734863
xarray_feature_center:
  coords: {}
  attrs: {}
  dims: {}
  data_vars:
    WaterLevel:
      dims: []
      attrs: {}
      data: 0.0919368788599968
    specific_humidity:
      dims: []
      attrs: {}
      data: 0.007285235915333033
    temperature:
      dims: []
      attrs: {}
      data: 286.80804443359375
